### ISSUE TITLE
If possible, search by vite hash or bsc hash

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-bridge-scan-frontend#3]
Enter the vite hash or bsc hash of this transaction, and display the bridge transaction in the result.
Or go directly to the details page of the bridge transaction.

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/48586082/162693295-675b9bfc-d0ce-4d3c-8f29-9f754fedd19c.png">

**Comment by 0xkarl** [comment]
Done. Also implemented 404 state:

<img width="1433" alt="Screenshot 2022-04-11 at 23 15 52" src="https://user-images.githubusercontent.com/82267178/162824464-3fab718d-2c59-4c83-8d4d-ea98572632fd.png">
i

**Comment by 0xkarl** [comment]
Done. Please confirm and close.
