### ISSUE TITLE
Front-end optimization

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-bridge-scan-frontend#4]
Change the template and add some other information, for example, number of assets supported by bridge, the number of supported chains, the curve of daily transaction volume, etc,

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/48586082/162694086-7e61863e-5d21-46a9-aab4-f7f74c4e385c.png">

**Comment by 0xkarl** [comment]
I think this now looks good..
