### ISSUE TITLE
bridge confirmation number problem

### ISSUE THREAD

**Issue by TerrAcoHee** [0xkarl/vite-bridge-scan-frontend#5]
When the bridge has not been completed, the browser has seen it completed

![image](https://user-images.githubusercontent.com/48586082/162694221-ef2fc2a2-2173-4972-82c9-35b5d412c42b.png)

![image](https://user-images.githubusercontent.com/48586082/162694245-595ea819-2a03-4184-8d6c-8cea6bb34da5.png)

**Comment by 0xkarl** [comment]
Done. Please confirm and close.
